### ISSUE TITLE
everytime i download this pugin from pmmp i get a crashdump

### ISSUE THREAD

**Issue by Pitstopers** [DaPigGuy/PiggyCustomEnchants#15]
this is what the crashdump say 07:20:16 [CRITICAL] ErrorException: "Declaration of PiggyCustomEnchants\CustomEnchants\CustomEnchants::setLevel($level) should be compatible with pocketmine\item\enchantment\Enchantment::setLevel(int $level)" (EXCEPTION) in "/PiggyCustomEnchants.phar/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants" at line 226
07:20:16 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
07:20:16 [EMERGENCY] Please upload the "C:\Users\pitstopers\Desktop\all\my mcpe server\crashdumps/Tue_Jun_20-07.20.16-ACT_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
how can i fix this

**Comment by BrianZP** [comment]
Its seems to be an issue with your Enchantment.php. can you provide me the src of your server software I might be able to fix that.

**Comment by Pitstopers** [comment]
Ok I send it

**Comment by Pitstopers** [comment]
https://drive.google.com/open?id=0BxweL9_p1bmDNkowOHpoQWJnclU here the src i use for my server

**Comment by Pitstopers** [comment]
Piggy can you fix this

**Comment by BrianZP** [comment]
There are two things I would like to conclude after seeing your src and Enchantment.php.
1. You are undoubtedly, not using the latest build of PocketMine-MP, download the latest one from <a href= "https://jenkins.pmmp.io/job/PocketMine-MP/">here</a>.
2. Also use the latest build of <a href= "https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants">PiggyCustomEnchants</a>.

Try updating to latest version and see if it fixes the issue. Furthermore if you still face the issue do upload the crash dump on <a href= "https://gist.github.com/">Gist</a> and provide a link here otherwise close the issue.

**Comment by Pitstopers** [comment]
But I thought this plugin supports tesseract and other spoons

**Comment by DaPigGuy** [comment]
We don't support Tesseract.

**Comment by Pitstopers** [comment]
What do you support

**Comment by BrianZP** [comment]
PocketMine-MP and PocketMine-MP only!!
