### ISSUE TITLE
Custom Enchant Suggestions

### ISSUE THREAD

**Issue by DarkIceTitan** [DaPigGuy/PiggyCustomEnchants#62]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

It would be nice if you add this to your list on to make enchants...

1. Blessed - max level 3 - adds a 8% chance to remove all debuffs per level [Weapon]

2. Enraged - max level 5 - add strength 2 per level example : enraged 2 would give me strength 4. [Armor]

#### **Steps to Reproduce the Issue**

1.

**Comment by DarkIceTitan** [comment]
It would be nice if you add this to your list on to make enchants...

1. Blessed - max level 3 - adds a 8% chance to remove all debuffs per level [Weapon]

2. Enraged - max level 5 - add strength 2 per level example : enraged 2 would give me strength 4. [Armor]

**Comment by DarkIceTitan** [comment]
[Sorry I'm new to github I didn't know how to post lol]

**Comment by DaPigGuy** [comment]
What about rarities? =)

**Comment by DaPigGuy** [comment]
Also, I've edited your comments into one.

**Comment by DarkIceTitan** [comment]
Oh, yes..Blessed should be mythical while enraged as a rare..

**Comment by Aericio** [comment]
@DarkIceTitan Do you have a link to where credit is being stolen?

**Comment by QuiverlyRivalry** [comment]
@DarkIceTitan he didnt steal anything I am sure, he just starred it.

By the way I am not hating PiggyCE, what I might ask might be huge work, but I jsut have an idea.
Custom means made specificly for someone.

What happens if you could do this, /ce create armour Enraged

You then get this messege sent: Enraged created, please choose what it should do. A. Give an effect B. Run a command (Functions) C. Spawn a block

Lets go with the hardest here. So pretend I typed C.

It says this, Please choose a block.
I type dirt.

Then says what chance, I say 40.

So when player hit, it has a 40% chance of spawning dirt...

Or is this too Custom xP

**Comment by QuiverlyRivalry** [comment]
Also sorry for spam @DaPigGuy but any future with /combine and enchanted books?

**Comment by Aericio** [comment]
@QuiverlyRivalry `Custom` in this case is referring to custom enchantments, which is basically a term used for enchantments not from vanilla. This wasn't made for someone, it was an open-source project for everyone. (well, technically was made for my factions server before i gave up on it.)

**Comment by DarkIceTitan** [comment]
Rivalry...He suggested the heavy,armored,and tank custom enchants.

Then on his servers forums he's saying he is coding them.

**Comment by DaPigGuy** [comment]
Also, this has been added to the todo list.

**Comment by QuiverlyRivalry** [comment]
@Aericio you had a factions server?? Im tryna make a comeback for Kingdoms craft..? Heard of it :p?

**Comment by Aericio** [comment]
@QuiverlyRivalry No, I don't really care however.

**Comment by DarkIceTitan** [comment]
DaPigGuy, I was replying to rivalry's comment.
